<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="description" content="Desenvolvimento e soluções em Tecnologias Web. Paulo Cesar Web"/>
        <meta name="description" content="Desenvolvimento e soluções em Tecnologias Web. Paulo Cesar Web"/>
        <meta name="keywords" content="desenvolvimento, php, tecnologia, paulo, cesar, web, hendges, programação, soluções, junior hendges, personal, institucional"/>
        <meta name="robots" content="index, follow, noarquive, noimageindex">
        <meta name="author" content="Paulo Cesar Hendges">
        <title>Paulo Cesar Hendges - Web Site</title>

        <!-- CSS  -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="<?= $this->url->getBaseUri() ?>materialize/materialize/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link rel="icon" type="image/png" href="<?= $this->url->getBaseUri() ?>img/icon.png">
        <link href="<?= $this->url->getBaseUri() ?>css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
        <link href="<?= $this->url->getBaseUri() ?>css/responsive.css" type="text/css" rel="stylesheet" media="screen,projection"/>

        <!--  Scripts-->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="<?= $this->url->getBaseUri() ?>inputmask/dist/jquery.inputmask.bundle.js"></script>
        <script src="<?= $this->url->getBaseUri() ?>materialize/materialize/js/materialize.js"></script>
        <script src="<?= $this->url->getBaseUri() ?>js/init.js"></script>

        <script src="<?= $this->url->getBaseUri() ?>jquery-validation/dist/jquery.validate.js"></script>
    </head>
    <body>
        <div class="navbar-fixed">
            <nav class="white" role="navigation">
                <div class="nav-wrapper container">
                    <a id="logo-container" href="#" class="brand-logo" title="Paulo Cesar Web"><<span class="red-text">PH</span><bold>?</bold><span class="cor-texto-default">Web></span></a>
                    <ul class="right hide-on-med-and-down links-navegacao"> 
                        <li><a href="#sobre" class="cor-texto-default nav-links">SOBRE MIM</a></li>
                        <li><a href="#formacao" class="cor-texto-default nav-links">FORMAÇÃO</a></li>
                        <li><a href="#profissional" class="cor-texto-default nav-links">PROFISSIONAL</a></li>
                        <li><a href="#galeria" class="cor-texto-default nav-links">GALERIA</a></li>
                        <li><a href="#contato" class="cor-texto-default nav-links">CONTATO</a></li>
                    </ul>
                    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons left">menu</i></a>
                </div>
            </nav>
        </div>
        <ul id="nav-mobile" class="side-nav links-navegacao">
            <li><a href="#sobre" class="cor-texto-default nav-links">SOBRE MIM</a></li>
            <li><a href="#formacao" class="cor-texto-default nav-links">FORMAÇÃO</a></li>
            <li><a href="#profissional" class="cor-texto-default nav-links">PROFISSIONAL</a></li>
            <li><a href="#galeria" class="cor-texto-default nav-links">GALERIA</a></li>
            <li><a href="#contato" class="cor-texto-default nav-links">CONTATO</a></li>
        </ul>

        <div id="index-banner" class="parallax-container">
            <div class="section no-pad-bot">
                <div class="container">
                    <div class="row">
                        <div class='col s12'>
                            <h1 class="header center white-text text-lighten-2 left">
                                <img src="<?= $this->url->getBaseUri() ?>img/php-iniciante2.png" class="responsive-img img-home">
                            </h1>
                        </div>
                        <div class='col s12'>
                            <img src="<?= $this->url->getBaseUri() ?>img/php-iniciante3.png" class="responsive-img img-home">
                        </div>
                    </div>
                </div>
            </div>
            <div class="parallax"><img src="<?= $this->url->getBaseUri() ?>img/home.jpg" style=""></div>
        </div>

        <!-- SOBRE -->
        <div class="container">
            <div class="section">
                <div class="row" >
                    <div class="col s12 center">
                        <div id="sobre" class="section scrollspy">
                            <h5 class="cor-texto-default"><ins>SOBRE MIM</ins></h5>
                        </div>
                        <div class="col s12 m4 div-sobre">
                            <fieldset>
                                <legend>
                                    <div class="icon-preview valign-wrapper legend-espacamento">
                                        <i class="material-icons small">wc</i> <span style="margin-left: 10px;">MINHA FAMÍLIA</span>
                                    </div>
                                </legend>
                                <p class="left-align light">
                                    Atualmente moro com minha Mãe e com meu Irmão caçula. Meu pai mora sozinho e sempre que podemos fazemos alguns eventos juntos. Tenho um filho de 4 anos e
                                    estou em um relacionamento a 2 anos e 4 meses com uma pessoa incrível. Gosto de reuniões familiares e admiro as coisas simples da vida.
                                </p>
                            </fieldset>
                        </div>
                        <div class="col s12 m4 div-sobre">
                            <fieldset>
                                <legend>
                                    <div class="icon-preview valign-wrapper legend-espacamento">
                                        <i class="material-icons small">mood</i> <span style="margin-left: 10px;">QUEM SOU EU ?</span>
                                    </div>
                                </legend>
                                <p class="left-align light">
                                    Meu nome é Paulo Cesar Santos Hendges Júnior e tenho 23 anos de idade. Nasci em Agosto de 1994 na cidade de Porto Alegre/RS e me criei em Viamão/RS, cidade vizinha. Estou concluíndo minha
                                    primeira graduação na área de Tecnologia da Informação e sou técnico em informática. Atualmente trabalho como Programador Pleno desenvolvendo e dando manutenção em aplicações Web.
                                    Sou uma pessoa muito tranquila, gosto de estar com a família rodeado pelas pessoas que eu admiro e amo. Foco sempre no trabalho em equipe e a boa comunicação entre as pessoas, acredito que este seja
                                    o principal fundamento para o sucesso de uma empresa.
                                </p>
                            </fieldset>
                        </div>
                        <div class="col s12 m4 div-sobre">
                            <fieldset>
                                <legend>
                                    <div class="icon-preview valign-wrapper legend-espacamento">
                                        <i class="material-icons small">videogame_asset</i> <span style="margin-left: 10px;">DIVERSÃO</span>
                                    </div>
                                </legend>
                                <p class="left-align light">
                                    Tenho como Hobby os gostos por pescaria, futebol, jogos online e outras coisas simples como um cinema, passeio à parques, fazer uma comida diferente,
                                    dentre outros. Sempre que possível gosto de fazer um programa diferente junto dos meus familiares. Uma coisa que me diverte muito é a pescaria, aprendi com o meu pai e levo comigo para sempre.
                                </p>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr style="height: 10px;" class="cor-default">

        <!-- Educacional -->
        <div class="container">
            <div class="section">
                <div class="row" >
                    <div class="col s12 center">
                        <div id="formacao" class="section scrollspy">
                            <h5 class="cor-texto-default"><ins>FORMAÇÃO</ins></h5>
                        </div>
                        <div class="col s12 m4 div-profissional">
                            <div class="col s12">
                                <div class="icon-preview legend-espacamento center">
                                    <span style="vertical-align: middle;">ENSINO MÉDIO</span>
                                    <i class="material-icons" style="vertical-align: middle; margin-left: 5px;">import_contacts</i>
                                </div>
                                <div class="card" style="overflow: visible;">
                                    <div class="card-image waves-effect waves-block waves-light">
                                        <img class="activator" src="<?= $this->url->getBaseUri() ?>img/ensinomedio.jpg">
                                    </div>
                                    <div class="card-content">
                                        <span class="card-title activator cor-texto-default">E.E.E Fundamental Almirante Bacelar</span>
                                    </div>
                                    <div class="card-reveal" style="display: none; transform: translateY(0px);">
                                        <span class="card-title grey-text text-darken-4">Formação - Ensino Médio<i class="material-icons right formacao-close">close</i></span>
                                        <p style="text-align: justify">Completei minha educação fundamental no ano de 2011 pela Escola Estadual de Ensino Fundamental Almirante Bacelar, localizada na Av. Protásio Alves, 13097 - Passo Dornelles, Porto Alegre - RS. Foi o lugar de onde partiram minhas primeiras grandes amizades e que algumas carrego até hoje.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4 div-profissional">
                            <div class="col s12">
                                <div class="icon-preview legend-espacamento center">
                                    <span style="vertical-align: middle;">CURSO TÉCNICO</span>
                                    <i class="material-icons" style="vertical-align: middle; margin-left: 5px;">build</i>
                                </div>
                                <div class="card" style="overflow: visible;">
                                    <div class="card-image waves-effect waves-block waves-light">
                                        <img class="activator" src="<?= $this->url->getBaseUri() ?>img/ensinotecnico.jpg">
                                    </div>
                                    <div class="card-content">
                                        <span class="card-title activator cor-texto-default">Alcides Maya - Faculdade e Escola Técnica</span>
                                    </div>
                                    <div class="card-reveal" style="display: none; transform: translateY(0px);">
                                        <span class="card-title grey-text text-darken-4">Formação - Curso Técnico<i class="material-icons right formacao-close">close</i></span>
                                        <p style="text-align: justify">Concluí meu Ensino Técnico em Informática no ano de 2012, pela Escola Técnica Alcides Maya localizada na Rua Doutor Flores, 396 - Centro Histórico, Porto Alegre - RS. Foi então que comecei a ter meus primeiros contatos profissionais com a área de técnologia da informação.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col s12 m4 div-profissional">
                            <div class="col s12">
                                <div class="icon-preview legend-espacamento center">
                                    <span style="vertical-align: middle;">ENSINO SUPERIOR (Concluindo)</span>
                                    <i class="material-icons" style="vertical-align: middle; margin-left: 5px;">school</i>
                                </div>
                                <div class="card" style="overflow: visible;">
                                    <div class="card-image waves-effect waves-block waves-light">
                                        <img class="activator" src="<?= $this->url->getBaseUri() ?>img/ensinotecnologo.jpg">
                                    </div>
                                    <div class="card-content">
                                        <span class="card-title activator cor-texto-default">Centro Universitário Leonardo Da Vinci</span>
                                    </div>
                                    <div class="card-reveal" style="display: none; transform: translateY(0px);">
                                        <span class="card-title grey-text text-darken-4">Formação - Tecnólogo<i class="material-icons right formacao-close">close</i></span>
                                        <p style="text-align: justify">Estou cursando o último semestre do Tecnólogo em Análise e Desenvolvimento de Sistemas pela Uniasselvi - Centro Universitário Leonardo Da Vinci.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="parallax-container valign-wrapper">
            <div class="section section-profissional">
                <div class="container">
                    <div class="row center">
                        <div class="row" >
                            <div class="col s12 center">
                                <div class="col s12">
                                    <div id="profissional" class="section scrollspy">
                                        <h5 class="" style="color: #064809 !important"><ins>PROFISSIONAL</ins></h5>
                                    </div>
                                </div>
                                <div class="col s12">
                                    <ul class="collapsible collapsible-accordion " data-collapsible="accordion" style="border: none !important">
                                        <li class="">
                                            <div class="collapsible-header valign-wrapper" style="background-color: transparent;border-left: 1px solid;border-top: 1px solid;border-right: 1px solid;">
                                                <i class="material-icons">
                                                    <img src="<?= $this->url->getBaseUri() ?>img/keyboard.png" style="width: 35px;">
                                                </i>
                                                <span class="legend-espacamento" style="color: white; font-size: 18px !important;">Desenvolvimento</span>
                                            </div>
                                            <div class="collapsible-body" style="display: none; border: 1px solid !important; border-top: none !important;">
                                                <span>
                                                    <div class="row">
                                                        <div class="col s12 m3 conhecimentos">
                                                            <div class="chip" style="background-color: transparent;color: white !important;">
                                                                <img src="<?= $this->url->getBaseUri() ?>img/php-icon.png"> PHP
                                                            </div>
                                                        </div>
                                                        <div class="col s12 m3 conhecimentos">
                                                            <div class="chip" style="background-color: transparent;color: white !important;">
                                                                <img src="<?= $this->url->getBaseUri() ?>img/jquery.png"> JQuery
                                                            </div>
                                                        </div>
                                                        <div class="col s12 m3 conhecimentos">
                                                            <div class="chip" style="background-color: transparent;color: white !important;">
                                                                <img src="<?= $this->url->getBaseUri() ?>img/css-icon.png"> CSS3
                                                            </div>
                                                        </div>
                                                        <div class="col s12 m3 conhecimentos">
                                                            <div class="chip" style="background-color: transparent;color: white !important;">
                                                                <img src="<?= $this->url->getBaseUri() ?>img/html-icon.png"> HTML5
                                                            </div>
                                                        </div>
                                                    </div>
                                                </span>
                                            </div>
                                        </li>
                                        <li class="">
                                            <div class="collapsible-header valign-wrapper" style="background-color: transparent;border-left: 1px solid;border-top: 1px solid;border-right: 1px solid;">
                                                <i class="material-icons">
                                                    <img src="<?= $this->url->getBaseUri() ?>img/web.png" style="width: 35px;">
                                                </i>
                                                <span class="legend-espacamento" style="color: white; font-size: 18px !important;">Design</span>
                                            </div>
                                            <div class="collapsible-body" style="display: none; border: 1px solid !important; border-top: none !important;">
                                                <div class="row">
                                                    <div class="col s12 m4 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/bootstrap.png" > Bootstrap
                                                        </div>
                                                    </div>
                                                    <div class="col s12 m4 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/materialize.png" > MaterializeCSS
                                                        </div>
                                                    </div>
                                                    <div class="col s12 m4 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/photoshop.png" > Photoshop
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="">
                                            <div class="collapsible-header valign-wrapper" style="background-color: transparent;border-left: 1px solid;border-top: 1px solid;border-right: 1px solid;">
                                                <i class="material-icons">
                                                    <img src="<?= $this->url->getBaseUri() ?>img/framework.png" style="width: 35px;">
                                                </i>
                                                <span class="legend-espacamento" style="color: white; font-size: 18px !important;">Frameworks</span>
                                            </div>
                                            <div class="collapsible-body" style="display: none; border: 1px solid !important; border-top: none !important;">
                                                <div class="row">
                                                    <div class="col s12 m6 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/zend.png" > Zend Framework
                                                        </div>
                                                    </div>
                                                    <div class="col s12 m6 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/phalcon.png" > Phalcon Framework
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        <li class="">
                                            <div class="collapsible-header valign-wrapper" style="background-color: transparent;border-left: 1px solid;border-top: 1px solid;border-right: 1px solid;">
                                                <i class="material-icons">
                                                    <img src="<?= $this->url->getBaseUri() ?>img/database.png" style="width: 35px;">
                                                </i>
                                                <span class="legend-espacamento" style="color: white; font-size: 18px !important;">Banco de Dados</span>
                                            </div>
                                            <div class="collapsible-body" style="display: none; border: 1px solid !important; border-top: none !important;">
                                                <div class="row"> 
                                                    <div class="col s12 m4 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/mysql.png" > MYSQL
                                                        </div>
                                                    </div>
                                                    <div class="col s12 m4 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/oracle.png" > Oracle
                                                        </div>
                                                    </div>
                                                    <div class="col s12 m4 conhecimentos">
                                                        <div class="chip" style="background-color: transparent;color: white !important;">
                                                            <img src="<?= $this->url->getBaseUri() ?>img/sqlserver.png" > SQL Server
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="parallax"><img src="<?= $this->url->getBaseUri() ?>img/backgound5.jpg" alt="Unsplashed background img 2"></div>
        </div>

        <div class="container">
            <div class="section">
                <div class="row">
                    <div class="col s12 center-align">
                        <h3><i class="mdi-content-send brown-text"></i></h3>
                        <div id="galeria" class="section scrollspy">
                            <h5 class="cor-texto-default"><ins>GALERIA</ins></h5>
                        </div>
                        <div class="row">
                            <div class="col s12 m3 ">
                                <img class="responsive-img img1 hoverable" id="img1" src="<?= $this->url->getBaseUri() ?>img/pessoal/1.jpg" style="opacity: 0;">
                            </div>
                            <div class="col s12 m3">
                                <img class="responsive-img img2 hoverable" id="img2" src="<?= $this->url->getBaseUri() ?>img/pessoal/2.jpg" style="opacity: 0;"> 
                            </div>
                            <div class="col s12 m3">
                                <img class="responsive-img img3 hoverable" id="img3" src="<?= $this->url->getBaseUri() ?>img/pessoal/3.jpg" style="opacity: 0;"> 
                            </div>
                            <div class="col s12 m3">
                                <img class="responsive-img img4 hoverable" id="img4" src="<?= $this->url->getBaseUri() ?>img/pessoal/4.jpg" style="opacity: 0"> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <hr style="height: 10px;" class="cor-default">

        <div class="container" id="contato-container" style="">
            <div class="section">
                <div class="row">
                    <div class="col s12 center">
                        <h3><i class="mdi-content-send brown-text"></i></h3>
                        <div id="contato" class="section scrollspy">
                            <h5 class="cor-texto-default"><ins>CONTATO</ins></h5>
                        </div>
                        <div class="row">
                            <form name="formContato" method="POST" action="">
                                <div class="col s12">
                                    <div class="row">
                                        <div class="input-field col s12 m6 offset-m3">
                                            <input placeholder="Qual seu Nome ?" id="nome" name="nome" type="text">
                                            <label for="nome" class="label-padrao">Nome</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 m6 offset-m3">
                                            <input id="email" name="email" type="email" placeholder="Informe seu Endereço Eletrônico">
                                            <label for="email" class="">E-mail</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 m3 offset-m3">
                                            <input id="telefone" name="telefone" type="text" placeholder="Telefone para Contato" required="required" pattern="[0-9]+$">
                                            <label for="telefone" class="">Telefone</label>
                                        </div>
                                        <div class="col s12 m2">
                                            <p>
                                                <input type="checkbox" id="chk-id" name="whats" value="1"/>
                                                <label for="chk-id">Whatsapp?</label>
                                            </p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 m6 offset-m3">
                                            <textarea id="textarea" class="materialize-textarea font-select" name="textoContato" placeholder="O que você gostaria ?"></textarea>
                                            <label for="textarea" class="font-select">Mensagem</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12 m6 offset-m3">
                                            <button type="submit" class="btn-large waves-effect btn-contato waves-light" name="btnContato">Contato</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="page-footer cor-default">
            <div class="container">
                <div class="row">
                    <div class="col l6 s12">
                        <h5 class="white-text">Contate-me</h5>
                        <ul>
                            <li style="margin-right: 5px;">Telefone: <span class="brown-text text-lighten-3">(51) 99291-3632</span></li>
                            <li style="margin-right: 5px;">E-mail: <a href="mailto:paulo.hendges@gmail.com"><span class="brown-text text-lighten-3">paulo.hendges@gmail.com</span></a></li>
                        </ul>
                    </div>
                    <div class="col l3 s12">
                    </div>
                    <div class="col l3 s12">
                        <h5 class="white-text">Mídias Sociais</h5>
                        <ul style="display: inline-flex">
                            <li style="margin-right: 5px;"><a href="https://www.facebook.com/profile.php?id=100009370305348"><i class="material-icons" target="_blank"><img src="<?= $this->url->getBaseUri() ?>img/facebook.png" class="icons"></i></a></li>
                            <li style="margin-right: 5px;"><a href="https://www.instagram.com/juniorhendges/" target="_blank"><i class="material-icons"><img src="<?= $this->url->getBaseUri() ?>img/instagram.png" class="icons"></i></a></li>
                            <li style="margin-right: 5px;"><a href="https://github.com/paulohendges" target="_blank"><i class="material-icons"><img src="<?= $this->url->getBaseUri() ?>img/github.png" class="icons"></i></a></li>
                            <li style="margin-right: 5px;"><a href="https://www.linkedin.com/in/paulo-cesar-hendges-jr-2a521a6b/" target="_blank"><i class="material-icons"><img src="<?= $this->url->getBaseUri() ?>img/linkedin.png" width="45" height="45" class="icons"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    <a class="brown-text text-lighten-3" href="#!">Paulo Cesar Hendges @</a>
                </div>
            </div>
        </footer>
    </body>
</html>
