<?php 
?>
<div style="background-color: #ebecf7; background: #ebecf7; width: 80%; margin:auto">
    <fieldset>
        <legend align="center"> CONTATO - PH?WEB </legend>
        <table align="center" style="width: 100%; border: 1px solid; width: 30%">
            <tr>
                <td style="text-align: center;">
                    Nome: <?=$nome?>
                </td>
            </tr>
            <tr>
                <td style="text-align: center;">
                    E-mail: <?=$email?>
                </td>
            </tr>
            <tr>
                <td style="text-align: center;">
                    Telefone: <?=$telefone?>
                </td>
            </tr>
            <tr>
                <td style="text-align: center; ">
                    WhatsApp: <?=$whatsapp == 1 ? 'Sim' : 'Não'?>
                </td>
            </tr>
            <tr>
                <td style="text-align: center; font-weight: bold">Mensagem</td>
            </tr>
            <tr>
                <td style="text-align: justify; padding-left: 10px; padding-right: 10px">
                    <?=$mensagem?>
                </td>
            </tr>
        </table>
    </fieldset>
</div>
